version: 2.1

jobs:
  verify:
    docker:
      - image: realalknowles/assessment:v1
    steps:
      - checkout
      - run:
          name: "Verify Code Changes"
          command: "python -m unittest discover -v ./python"
  deploy:
    docker:
      - image: realalknowles/assessment:v1
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: "echo deploying"

workflows:
  verify-and-deploy:
    jobs:
      - verify
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - verify