version: 2.1

jobs:
  verify:
    docker:
      - image: realalknowles/assessment:v3
    steps:
      - checkout
      - run:
          name: "Verify Infrastructure Changes"
          command: | 
            cd ./terragrunt/assessment
            terragrunt plan --terragrunt-non-interactive
      - run:
          name: "Verify Code Changes"
          command: python -m unittest discover -v ./python
  deploy:
    docker:
      - image: realalknowles/assessment:v3
    steps:
      - checkout
      - run:
          name: "Deploy Infrastructure Changes"
          command: | 
            cd ./terragrunt/assessment
            terragrunt apply --terragrunt-non-interactive -auto-approve
      - run:
          name: "Deploy Code Changes"
          command: | 
            zip -r -j ./function.zip ./python/*
            awsv2 lambda update-function-code --function-name assessment-function --zip-file fileb://./function.zip
  test:
    docker:
      - image: realalknowles/assessment:v3
    steps:
      - run:
          name: "Test Function"
          command: |
            response_code=$(curl -s -o /dev/null -w "%{http_code}" https://assessment.realalknowles.com)
            if [ "$response_code" = "200" ]
            then
              echo "Deployment succeeded"
              exit 0
            fi
            
            echo "Deployment failed - response code was ${response_code}"
            exit 1

workflows:
  verify-and-deploy:
    jobs:
      - verify
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - verify
      - test:
          requires:
            - deploy