version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  verify:
    docker:
      - image: gruntwork/terragrunt:0.0.2
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "Verify Code Changes"
          command: "python -m unittest discover -v ./python"
  deploy:
    docker:
      - image: gruntwork/terragrunt:0.0.2
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: "echo deploying"

workflows:
  verify-and-deploy:
    jobs:
      - verify
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - verify