version: 2.1

jobs:
  verify:
    docker:
      - image: alpine/terragrunt:1.6.6
    steps:
      - checkout
      - run:
          name: "Verify"
          command: "echo verifying"
      - understand-path:
          name: "Understand path"
          command: "pwd && ls -al"
  deploy:
    docker:
      - image: alpine/terragrunt:1.6.6
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: "echo deploying"

workflows:
  verify-and-deploy:
    jobs:
      - verify
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - verify