version: 2.1

jobs:
  verify:
    docker:
      - image: alpine/terragrunt:1.6.6
    steps:
      - checkout
      - run:
          name: "Verify"
          command: "echo verifying"
  deploy:
    docker:
      - image: alpine/terragrunt:1.6.6
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: "echo deploying"
    filters:
      branches:
        only:
          - main

workflows:
  say-hello-workflow:
    jobs:
      - verify
      - deploy:
          requires:
            - verify