version: 2.1

jobs:
  verify:
    docker:
      - image: realalknowles/assessment:v3
    steps:
      - checkout
      - run:
          name: "Verify Code Changes"
          command: python -m unittest discover -v ./python
      - run:
          name: "Verify Infrastructure Changes"
          command: | 
            cd ./terragrunt/assessment
            terragrunt init --terragrunt-non-interactive
            terragrunt plan --terragrunt-non-interactive
  deploy:
    docker:
      - image: realalknowles/assessment:v3
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: echo "deploying"

workflows:
  verify-and-deploy:
    jobs:
      - verify
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - verify